### ISSUE TITLE
Not working with Objective C code

### ISSUE THREAD

**Issue by dis123** [cacmartinez/CCMRadarView#2]
I tried to implement swift code with my objective C code as per apple documentation how to integrate swift file in objective C code. I am using latest Xcode 6.3. Swift code is also trigger but not able to see the animation. I debug the code and found that in "override func animationDidStop(anim: CAAnimation!, finished flag: Bool)" the value of flag is always comes 'false' so that animation is not working with objective C code. Can you please look into this why I am not able to see the animation in objective C Code.

**Comment by yunxiaocloud** [comment]
I met the same question as your saying,if you find the solution,please write the solution in here.Thank you very much!

**Comment by udeysri** [comment]
It works for me ( Xcode 6.4 ) .. I have created a new swift file in my project called 'CCMRadarView.swift' , 
( you will be prompted to add an Objective-C bridging header & I accepted it )  & add the CCMRadarView.swift code in to it . 

But I have to change the class declaration " @IBDesignable class CCMRadarView: UIView"  to "@objc class CCMRadarView: UIView " as I'm using the swift code inside my objc code.

Then in my UIViewController.h / .m I have import the class as  #import "Project_Name-Swift.h" ( if your project name has spaces - "Project Name " or hyphens -"Project-Name" you need to add underscore " Project_Name" when importing the class. )

Then in your .m file -(void)viewDidAppear:(BOOL)animated{ } you can call "startAnimation" method . It will show the animation .. 

( In your build phases "project module name" should match with your "Project_Name" )

Hope this works for you ...

**Comment by cacmartinez** [comment]
Hi sorry for the late response, I have updated the project and podspecs to add support for objective-c, and to use the Swift 2.0 syntax. You can see the necessary imports you need to make for it to work with your code in the [Import Framework section](https://github.com/cacmartinez/CCMRadarView#importing-framework). I have tested it with XCode 7.1 in Objective-C
