### ISSUE TITLE
Question: Use without Storyboard

### ISSUE THREAD

**Issue by ghost** [cacmartinez/CCMRadarView#5]
I'm currently not using story board for my project. Would the CCMRadarView work the same way ?
I have added it to my project but The animating circles don't fade out as the example given. Please help.

**Comment by kelebra** [comment]
Sorry, I am really new to Swift, but I do have the same issue. I am using this library through pods and usage code is the following:

``` swift
let radar = welcomeScreenAnimation()
radar.startAnimation()
self.view.addSubview(radar)

func welcomeScreenAnimation() -> CCMRadarView {
        let bound = width() / 2
        let view = CCMRadarView(frame: CGRect(origin: CGPoint(x: width() / 2, y: height() / 4), size: CGSize(width: bound, height: bound)))
        view.radarColor = UIColor.whiteColor()
        view.center = self.view.center
        return view
    }
```

Can you please assist on what I am doing wrong? Thanks beforehand.
